Repository microsoft/vscode-cordova, pull requests merged in 2019-12, with the labels that each got.

#592 Small docs wordings fix
  README.md
Labels: documentation

#596 Deps: vscode-chrome-debug-core@6.8.7
  package-lock.json
  package.json
Labels: security

#597 Prepare for 1.9.1
  CHANGELOG.md
  ThirdPartyNotices.txt
  package-lock.json
  package.json
  release/ThirdPartyNotices.txt
Labels: prerelease
